# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        exclude: (template|ci).*\.(json|yml|yaml)$
  - repo: local
    hooks:
    - id: black
      name: black
      language: python
      types: [python]
      entry: poetry run black
      exclude: (notebooks/).*\.(json|yml|yaml).*\.(.gitignore)
    - id: pylint
      name: pylint
      entry: poetry run pylint
      types: [python]
      language: python
    - id: isort
      name: isort
      language: python
      types: [python]
      entry: poetry run isort --profile black
      exclude: (notebooks/).*\.(json|yml|yaml).*\.(.gitignore)
    - id: pytest
      name: pytest
      language: system
      entry: poetry run nox --session tests
      types: [python]
      pass_filenames: false
